name: Rebuild TIL Viewer
on:
  push:
    branches:
      - main
jobs:
  resize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create resized_image directory
        run: mkdir -p ./resized_image
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick
      - name: Resize images
        run: |
          find ./image -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) -exec sh -c '
            for img; do
              mkdir -p "./resized_image/$(dirname "$img" | sed "s|^./image||")"
              convert "$img" -resize 60% "./resized_image/${img#./image/}"
            done
          ' sh {} +
      - name: check resized images
        run: ls -l ./resized_image
      - name: Upload resized images as artifact
        uses: actions/upload-artifact@v3
        with:
          name: resized_images
          path: ./resized_image
  upload-to-s3:
    needs: resize-images
    runs-on: ubuntu-latest
    steps:
      - name: Download resized images artifact
        uses: actions/download-artifact@v3
        with:
          name: resized_images
          path: ./resized_image
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::093568989871:role/TILImageBucketUploadPolicy
          aws-region: ap-northeast-1
      - name: Upload images to S3
        run: |
          aws s3 sync ./resized_image s3://til-viewer-images --exact-timestamps
  run-repository-dispatch:
    needs: upload-to-s3
    runs-on: ubuntu-latest
    steps:
      - name: dispatch til-viewer deploy workflow
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GH_API_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/tamashiro-syuta/til-viewer/dispatches \
            -d '{"event_type":"update-til"}'
