name: Rebuild TIL Viewer
on:
  push:
    branches:
      - main
jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch til-viewer deploy workflow
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GH_API_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/tamashiro-syuta/til-viewer/dispatches \
            -d '{"event_type":"update-til"}'
